### ISSUE TITLE
Tracker Transfer

### ISSUE THREAD

**Issue by YueZhang-studyuse** [MAPF-Competition/PlanViz#11]
We want to add support for visualising mapf plans. The mapf tracker (http://tracker.pathfinding.ai/) is a database with many best-known mapf plans, but the format in which the plans appear is different to the one accepted by PlanViz.
Proposal: 
(1) extend PlanViz to accept mapf action model
(2) add a script/program to convert mapf tracker plans into PlanViz plans.

**Comment by YueZhang-studyuse** [comment]
Implemented in 
f7b99037636ab5ce709c4e0e366900873068667a

**Comment by YueZhang-studyuse** [comment]
The documentation for PlanViz and Tracker Transfer tools is very long, and should be split up.
Proposal:
(1) readme.md should contain the description of the two main program in the repo and the examples of how to run them. 
(2) details of instructions should be moved to seperate markdown files.
(3) the programs (plan_viz.py, tracker_transfer.py) live in the top folder of the repo, and other python files lives inside of source subfolder (src/)
(4) rename script folder to src

**Comment by dharabor** [comment]
Documentation changes currently on branch  ``mapf-dev``. @shchan13 you are the principal maintainer of the PlanViz repo. Any comments before we wrap this one up?

**Comment by shchan13** [comment]
I have checked the code and the documents. I think it would be better if we merge this into the main branch after we finish the render function for generating agents without dots for the vanilla MAPF.

**Comment by dharabor** [comment]
sounds good. it sounds like a minor change. could we get this done for
release early next week?
