### ISSUE TITLE
Debug documentation

### ISSUE THREAD

**Issue by YueZhang-studyuse** [MAPF-Competition/PlanViz#14]
we need a new section in PlanViz.md, called debugging your plans, which explains how to understand errors and how to use PlanViz to explore a solution by jumping to different time points.

**Comment by dharabor** [comment]
Where are we with this? @HanZhang39 ?

**Comment by HanZhang39** [comment]
I added a draft document in the StartKit repo.

**Comment by shchan13** [comment]
Please move the documents to PlanViz.md in dev branch. Thanks!
