### ISSUE TITLE
Task schedule visualisation support

### ISSUE THREAD

**Issue by YueZhang-studyuse** [MAPF-Competition/PlanViz#25]
We need to visualise the task schedule (planned schedule and actual schedule) for each timestep.

Things to consider:
(1) Now one task is more than one location, so we need to consider how to show the orders and different locations of one single task. -> we consider to mark the location as task_id.order.
Suggestions to handle this:

Show a task
- if having a list of tasks (maybe only tasks revealed or assigned at the current timestep, anyway, someway you can select a task)
- select a task
- grey all other elements on the visualiser, only left the selected task shown and in colour
- have order labelled on each task location/errand

Show tasks associated with an agent
- select an agent
- somewhere show a list of tasks assigned to this agent
- then you can select a task and show the task

(2) Separate Task assignments from events and add more panels for task errors.

(3) We run out of colors! so far we already use pink, orange, green, blue, grey, red.

(4) Keep task-related information minimal but useful.
- We might don't want a big list of all the tasks, as there may have too much tasks no one can work with it.
- We might only show tasks or information related to tasks for the current timestep, keeping information shown minimal but useful.

(5) Task assignment errors:
- Task assignment made but rejected by task manager

@shchan13 Please add more.

**Comment by nobodyczcz** [comment]
Aug 15:

Bugs:
- click the agent the tasks shown are not the current assigned/working task

What's missing:

- for current open task distinguish between finished errands and unfinished errands

UC1 Default view:
- agents are labeled with id,  show the next errand of the next task only

UC2 Agent Tracking:
- When click on an agent, planned path to reach the first errand of first task is shown. 
- Link subsequent errands and tasks (assigned to the select agent) with arrowed dash lines, swapping color between tasks.
![image](https://github.com/user-attachments/assets/328cf60f-8d8a-43a8-8c9d-32d38c0fe7d0)
- Allow select multiple agents (shift click), and show paths, linkes, tasks for all selected agents.
- Update paths, tasks, links as agent moves and tasks completed/assigned.
- Disappear finished errands.
- Click on no agent no task locations to unselect all agnets.

UC3 event list:
- in the event list, list all events happened at or before current timestep.

UC4 Assignment tasks:
- click a location, if multiple tasks share the location, show a list of related task and agents in a box on control panel
- Then allow user select an item in the box
- If select an item with related agent, similar to UC2 show paths, links, tasks for all tasks related assigned to the agent.
- click a task, if not assigned, just show links between errands of the task.
![image](https://github.com/user-attachments/assets/35273784-8507-4b44-b631-d2b9e61a3411)

**Comment by shchan13** [comment]
@YueZhang-studyuse and @nobodyczcz please fix the issue #58 in the start-kit and send me the new output.json so that the above tasks can be done.

**Comment by nobodyczcz** [comment]
2024-9-6 Comments:
- UC2:
  -  the visualisation only works in a static manner, we need to update the display while agent moves
  - arrow start from agent to  next errands and then between remainning errands
  - with a toggle to show paths or not on the panel
  - path off by default
  - lines that connect agent and errands be thiner, refer to keisuke's visualisation as a reference: https://kei18.github.io/

**Comment by nobodyczcz** [comment]
2024-9-13 Comments:

*UC1 Views:
- Default view:
  - ~~agents are labeled with id~~
  - ~~shown tasks selected as "current"~~
- Shown tasks drop down changes the view to:
  - ~~current: just next errand location of all agents~~
  - bugs on: assigned: current + all subsequent errands of tasks that are currently assigned to agents. 
  - bugs on: all: current + assigned + revealed but unassigned
- Task colouring: 
  - ~~next errand location of every agent is orange~~
  - ~~rest of errands of all assigned tasks is pink~~
  - pending tests: errands of revealed but unassigned tasks is light yellow, e.g.: #eeeaa2
  - ~~no task id numbers on the map~~


UC2:
- mostly done
- there are some small bugs, e.g. on errands not disappear after the agent arrives the errand

UC3:
- outstanding

**Comment by dharabor** [comment]
Comments from 2024-09-20

UC1: 
- **Default view:** done
- **Task colouring:** 
-- still not right; recap: next errand orange, remaining errands in the current task color pink, revealed but unassigned errands color #eeeaa2
-- fill in cells with colour completely.
- **Shown tasks drop down:** need to change order of drawing: revealed tasks first, then errands of assigned tasks, then next errand

UC2: 
- done 

UC3: 
- Still outstanding

**Comment by dharabor** [comment]
2024-10-18

We are still missing support for showing scheduler errors in the "errors list".  We need to add this feature. Propose the following:

1. Generate example json with errors from each of the scheduler error categories, as discussed in the [startkit documentation](https://github.com/MAPF-Competition/Start-Kit/blob/main/Prepare_Your_Submission.md)
2. Each error needs to appear in the errors list display element
3. We need to display/highlight  agents mentioned in the error
4. The colour of mentioned agents should be yellow (warning, not critical)
5. The agents are highlighted just for the timestep of the error event
