### ISSUE TITLE
Bug on loading a more complex json output

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/PlanViz#32]
When loading a larger output json we get an error, using the code in commit: commit 80f0f5ab99466295f21fa576734ff30689ae82dd (the head of tymViz_dev)

```
(base) ➜  PlanViz git:(tymViz_dev) python3 script/run2.py --map ../contest-server/debug_problems/2024/city.domain/maps/Paris_1_256.map --plan /Users/mche0112/Downloads/paris_1_256_250.json 
===== Initialize PlanConfig2 =====
Loading map from ../contest-server/debug_problems/2024/city.domain/maps/Paris_1_256.map... Done!
Loading paths... Done!
Loading errors... Done!
Loading tasks...Done!
Loading schedule...Loading event...Traceback (most recent call last):
  File "/Users/mche0112/Codes/PlanViz/script/run2.py", line 53, in <module>
    main()
  File "/Users/mche0112/Codes/PlanViz/script/run2.py", line 45, in main
    plan_config = PlanConfig2(args.map, args.plan, args.team_size, args.start, args.end,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mche0112/Codes/PlanViz/script/plan_config2.py", line 94, in __init__
    self.load_plan(plan_file)  # Load the results
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mche0112/Codes/PlanViz/script/plan_config2.py", line 284, in load_plan
    self.load_events(data)
  File "/Users/mche0112/Codes/PlanViz/script/plan_config2.py", line 230, in load_events
    self.seq_tasks[task_id].tasks[seq_id].events["finished"]["agent"] = ag_id
    ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 380
```

[paris_1_256_250.json](https://github.com/user-attachments/files/16987279/paris_1_256_250.json)

**Comment by YueZhang-studyuse** [comment]
the problem seems to happen due to in plan_config2.py, line 243-244 will stop reading when exceeding the end_tstep, while others (events loading, etc) will try to read all. which causes the key error of the task id.

**Comment by YueZhang-studyuse** [comment]
the function load_schedule() should also support of task_id = -1 (assign no task) for one agent.

**Comment by TachikakaMin** [comment]
> the problem seems to happen due to in plan_config2.py, line 243-244 will stop reading when exceeding the end_tstep, while others (events loading, etc) will try to read all. which causes the key error of the task id.

Fixed.

https://github.com/MAPF-Competition/PlanViz/blob/9b2d33e9482c3d28a53eee4699988872a912cb7f/script/plan_config2.py#L225


> the function load_schedule() should also support of task_id = -1 (assign no task) for one agent. Currently when reading this, it has errors.

I think it can do it since the task/agent arrays are actually dict.
