### ISSUE TITLE
Right click a cell show an agent not related to the cell

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/PlanViz#39]
Using the example/warehouse_small_2024.json plan.

If right click cell with label 17:
<img width="1451" alt="Screenshot 2024-11-17 at 8 56 16 PM" src="https://github.com/user-attachments/assets/01bdd4c0-61ee-45c8-872b-982092370cef">

It shows agent 17, but 17 never visits this cell:
<img width="1446" alt="Screenshot 2024-11-17 at 8 56 44 PM" src="https://github.com/user-attachments/assets/d6022e50-a6e0-43b8-88c0-bb8be4bcfe3b">

**Comment by nobodyczcz** [comment]
@TachikakaMin I pulled your changes but found nothing happens if I right click a location (including locations with tasks)

**Comment by TachikakaMin** [comment]
try ctrl+rightclick? @nobodyczcz
