### ISSUE TITLE
Heat Map

### ISSUE THREAD

**Issue by nobodyczcz** [MAPF-Competition/PlanViz#5]
Proposal:

- Given the execution plan, we build a histogram that shows the usage of each location on the map.
- We visualise the histogram on the map by colouring tiles from white (never occupied) to red (every timestep the tiles is occupied by agents). white (r:255,g:255,b:255), red(r:255,g:0,b:0)
- Options on always showing heat map across all previous timesteps or just last k timestep (k could be current visualiser timestep).

**Comment by shchan13** [comment]
Done.
