### ISSUE TITLE
Support for different agent models

### ISSUE THREAD

**Issue by YueZhang-studyuse** [MAPF-Competition/PlanViz#6]
Currently, the agent model is implicit, it supports the forward displacement of one unit, and it supports rotation by 90 degrees. We want to make the model explicit and describe the actions in a text file.

sketch:

plan symbol followed by drawing instructions (rotation, displacement).
the shape of the agent on the grid (square or round plus radius, other abstract shapes made of simple squares).
the drawing instructions are keywords followed by numeric parameters.
Example:
MODEL [name (eg. MAPF, MAPF_T)]
SHAPE [circle | square | sprite file] [radius]

REQUIREMENT [orientation ... ... ]

[PLANSYMBOL]
ROTATE [radians]

[PLANSYMBOL]
DISPLACEMENT [delta x][delta y]

[PLANSYMBOL]
FORWARD_DISPLACEMENT [distance]

[PLANSYMBOL]
ROTATE [radians]
DISPLACEMENT [delta x][delta y]

**Comment by nobodyczcz** [comment]
Example for MAPF_T:

MODEL MAPF_T
SHAPE circle 0.5

F

**Comment by nobodyczcz** [comment]
What does ros do?

**Comment by nobodyczcz** [comment]
Give examples of things that cannot be described in this way.

**Comment by nobodyczcz** [comment]
Look at how PDDL+ does.
