### ISSUE TITLE
Better pointer support

### ISSUE THREAD

**Issue by YueZhang-studyuse** [MAPF-Competition/PlanViz#9]
add support to handle the following functionality with the trackpad:
(1) zoom
(2) click and drag
(3) pan and scroll
(4) right click
 (if tkinter does not support this, maybe add some additional keyboard shortcut to support this)

**Comment by shchan13** [comment]
Unfortunately, I don't have a trackpad.

**Comment by nobodyczcz** [comment]
One intermediate solution is binding all events to keyboard shortcuts:

1. zoom in: ctrl + "="
2. zoom out: ctrl + "-"
3. move camera on canvas: using arrow keys or  "hjkl" or "wsad"
4. Allow left click to select an agent and shift + click to select additional agents.
5. Show paths/agent details for selected agents with key "p"

Improve key binding on mac:

- https://stackoverflow.com/questions/30668425/tkinter-right-click-popup-unresponsive-on-osx

**Comment by YueZhang-studyuse** [comment]
Improve key binding on mac is done with commit dd11206edf7154122d2271ac78a29f67940332f1

**Comment by YueZhang-studyuse** [comment]
add a keyboard shortcut for reset (eg. backspace)

**Comment by YueZhang-studyuse** [comment]
done with commit 841f034c7708b3bfd15096e8df2263152e323ac1

**Comment by shchan13** [comment]
After implementing the heatmap, I tried to merge the dev branch but got an error when clicking the reset button.
